### ISSUE TITLE
issues with url parsing if Axis camera

### ISSUE THREAD

**Issue by reijosirila** [mbullington/yellowstone#29]
Sample program
```
const { RTSPClient, H264Transport } = require('yellowstone');

// User-specified details here.
const url = "rtsp://192.168.1.1/axis-media/media.amp";
const username = undefined;
const password = undefined;

const client = new RTSPClient(username, password);

client.connect(url, { keepAlive: true, connection: 'tcp'  })
  .then(details => {
    console.log("Connected. Video format is", details.codec);
    client.play();
  })
  .catch(e => console.log('Error::::', e));

// The "data" event is fired for every RTP packet.
client.on("data", (channel, data, packet) => {
  console.log("RTP:", "ID=" + packet.id, "TS=" + packet.timestamp, "M=" + packet.marker);
});

// The "controlData" event is fired for ever RTCP packet.
client.on("controlData", (channel, rtcpPacket) => {
  console.log("RTCP:", "TS=" + rtcpPacket.timestamp, "PT=" + rtcpPacket.packetType);
});

client.on('log', log => {
  console.log('#### log', log);
})
```
Output:
```
rmackbook:h264-test2 reijo$ node index.js 
#### log OPTIONS rtsp://192.168.1.1/axis-media/media.amp RTSP/1.0
CSeq: 1
User-Agent: yellowstone/3.x

#### log RTSP/1.0 200 OK
CSeq: 1
Public: OPTIONS, DESCRIBE, GET_PARAMETER, PAUSE, PLAY, SETUP, SET_PARAMETER, TEARDOWN
Server: GStreamer RTSP server
Date: Sat, 19 Sep 2009 22:04:50 GMT


#### log DESCRIBE rtsp://192.168.1.1/axis-media/media.amp RTSP/1.0
CSeq: 2
User-Agent: yellowstone/3.x
Accept: application/sdp

#### log v=0
o=- 797688409766834164 1 IN IP4 192.168.1.1
s=Session streamed with GStreamer
i=rtsp-server
t=0 0
a=tool:GStreamer
a=type:broadcast
a=range:npt=now-
a=control:rtsp://192.168.1.1/axis-media/media.amp
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:50000
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4d0029;sprop-parameter-sets=Z00AKeKQCgC3YC3AQEBpB4kRUA==,aO48gA==
a=control:rtsp://192.168.1.1/axis-media/media.amp/stream=0
a=framerate:10.000000
a=transform:-1.000000,0.000000,0.000000;0.000000,-1.000000,0.000000;0.000000,0.000000,1.000000
v=0
o=- 797688409766834164 1 IN IP4 192.168.1.1
s=Session streamed with GStreamer
i=rtsp-server
t=0 0
a=tool:GStreamer
a=type:broadcast
a=range:npt=now-
a=control:rtsp://192.168.1.1/axis-media/media.amp
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:50000
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4d0029;sprop-parameter-sets=Z00AKeKQCgC3YC3AQEBpB4kRUA==,aO48gA==
a=control:rtsp://192.168.1.1/axis-media/media.amp/stream=0
a=framerate:10.000000
a=transform:-1.000000,0.000000,0.000000;0.000000,-1.000000,0.000000;0.000000,0.000000,1.000000

#### log SETUP rtsp://192.168.1.1/axis-media/media.amp/rtsp://192.168.1.1/axis-media/media.amp/stream=0 RTSP/1.0
CSeq: 3
User-Agent: yellowstone/3.x
Transport: RTP/AVP/TCP;interleaved=0-1

#### log RTSP/1.0 404 Not Found
CSeq: 3
Server: GStreamer RTSP server
Date: Sat, 19 Sep 2009 22:04:51 GMT


Error:::: Error: Bad RTSP status code 404!
    at RTSPClient.responseHandler (/Users/reijo/dev/larva.io/h264-test2/node_modules/yellowstone/dist/RTSPClient.js:256:28)
    at emitThree (events.js:141:20)
    at RTSPClient.emit (events.js:217:7)
    at RTSPClient._onData (/Users/reijo/dev/larva.io/h264-test2/node_modules/yellowstone/dist/RTSPClient.js:403:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```
Changing url to `const url = "rtsp://192.168.1.1/axis-media/media.amp?";` 
it works but urls are still parsed wrongly. 

rmackbook:h264-test2 reijo$ node -v
v8.11.2

**Comment by RogerHardiman** [comment]
This is now fixed in the source code on github.
The SDP contained a 'absolute media stream URL' ie
  a=control:rtsp://192.168.1.1/axis-media/media.amp/stream=0

This is valid, but Yellowstone did not handle the case.

So the SETUP command should have been
```log SETUPrtsp://192.168.1.1/axis-media/media.amp/stream=0 RTSP/1.0```

and not 
```log SETUP rtsp://192.168.1.1/axis-media/media.amp/rtsp://192.168.1.1/axis-media/media.amp/stream=0 RTSP/1.0```
