### ISSUE TITLE
ReferenceError: _onData is not defined

### ISSUE THREAD

**Issue by ghost** [mbullington/yellowstone#5]
I downloaded the module with command:
`npm install yellowstone --save`
Starting an example in /examples/wowza.js with command `node wowza.js` gives me an error:

```
C:\Users\user\Documents\test\node_modules\yellowstone\examples>node wowza.js
C:\Users\user\Documents\test\node_modules\yellowstone\dist\rtsp.js:167
          client.on('data', _onData);
                            ^

ReferenceError: _onData is not defined
    at Socket.<anonymous> (C:\Users\user\Documents\test\node_modules\yellow
stone\dist\rtsp.js:167:29)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1045:10)
```

Using node.js v.4.1.1

**Comment by mbullington** [comment]
It's been fixed, if you're using Node v6 now, feel free to try out v2.0.0!

(it's actually a properly working library, superior in every way, unlike what this one was).
