### ISSUE TITLE
Exception has occurred: Error: Bug in RTSP data framing, please file an issue with the author with stacktrace

### ISSUE THREAD

**Issue by ckir** [mbullington/yellowstone#60]
`
Trace
    at eval (eval at _onData (c:\!PORTABLES\RTSP\RTSPWatchdog\node_modules\yellowstone\dist\RTSPClient.js:428:17), <anonymous>:1:9)
    at RTSPClient._onData (c:\!PORTABLES\RTSP\RTSPWatchdog\node_modules\yellowstone\dist\RTSPClient.js:428:17)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
`
The url of the particular RTSP tream is "rtsp://IP-ADDRESS/user=USERNAME_password=PASSWORD_channel=1_stream=1.sdp?real_stream"

**Comment by RogerHardiman** [comment]
what make and model of camera are you using?

**Comment by ckir** [comment]
Please see the requested information here
[https://drive.google.com/file/d/16WGhbTmTZZYqpx6_NXrvHB6D7PR5CjsY/view?usp=sharing](url)
It works fine with VLC and other players. I can give you direct access to the camera if you want to

**Comment by RogerHardiman** [comment]
Hi
remote access would be handy.
It would be interesting to log VLC and see if it also has problems, but just reconnects and moves on without complaining.
If you want to email me some details then it is
   rogerhardiman
   at      gmail   dot com

How often do you get the problem? (how long will I need to wait to see the issue?)

Thanks
Roger

**Comment by RogerHardiman** [comment]
Hi there
Thanks for the email confirming that things are now working with the camera.

Roger
